// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCStTKgE1-M2Naey-0FzyilkHcqj2-Mp0w',
    appId: '1:1045938620720:web:44254cf2685b4e0a3ae0f5',
    messagingSenderId: '1045938620720',
    projectId: 'donorbuddy-83cb3',
    authDomain: 'donorbuddy-83cb3.firebaseapp.com',
    storageBucket: 'donorbuddy-83cb3.appspot.com',
    measurementId: 'G-SJXDV3S2V7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5iCzcUeWOYQobj27qoeL3dYNagf5r4O8',
    appId: '1:1045938620720:android:693b9f7b907d071c3ae0f5',
    messagingSenderId: '1045938620720',
    projectId: 'donorbuddy-83cb3',
    storageBucket: 'donorbuddy-83cb3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2sIfUntgFdjpbCMtVDc33EUQLQdODkW0',
    appId: '1:1045938620720:ios:816444c6abb773c03ae0f5',
    messagingSenderId: '1045938620720',
    projectId: 'donorbuddy-83cb3',
    storageBucket: 'donorbuddy-83cb3.appspot.com',
    iosBundleId: 'com.example.bda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2sIfUntgFdjpbCMtVDc33EUQLQdODkW0',
    appId: '1:1045938620720:ios:816444c6abb773c03ae0f5',
    messagingSenderId: '1045938620720',
    projectId: 'donorbuddy-83cb3',
    storageBucket: 'donorbuddy-83cb3.appspot.com',
    iosBundleId: 'com.example.bda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCStTKgE1-M2Naey-0FzyilkHcqj2-Mp0w',
    appId: '1:1045938620720:web:aa25dd0fe594b9fa3ae0f5',
    messagingSenderId: '1045938620720',
    projectId: 'donorbuddy-83cb3',
    authDomain: 'donorbuddy-83cb3.firebaseapp.com',
    storageBucket: 'donorbuddy-83cb3.appspot.com',
    measurementId: 'G-65GBB900GY',
  );

}