// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzMFKOadBS9xbT7r-fpQvPYEP9RySjgBo',
    appId: '1:698030383095:web:6c2f463bd1e5393d8998f2',
    messagingSenderId: '698030383095',
    projectId: 'abc-test-8a172',
    authDomain: 'abc-test-8a172.firebaseapp.com',
    storageBucket: 'abc-test-8a172.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPruwW7padndYfEa13oLfF34dtwe4EfXU',
    appId: '1:698030383095:android:b85d395dbc3032288998f2',
    messagingSenderId: '698030383095',
    projectId: 'abc-test-8a172',
    storageBucket: 'abc-test-8a172.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1NdkTFxXs0npu01ajI01YUSaHBWIouc4',
    appId: '1:698030383095:ios:0362135e1373a6028998f2',
    messagingSenderId: '698030383095',
    projectId: 'abc-test-8a172',
    storageBucket: 'abc-test-8a172.appspot.com',
    iosBundleId: 'com.example.bda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1NdkTFxXs0npu01ajI01YUSaHBWIouc4',
    appId: '1:698030383095:ios:0362135e1373a6028998f2',
    messagingSenderId: '698030383095',
    projectId: 'abc-test-8a172',
    storageBucket: 'abc-test-8a172.appspot.com',
    iosBundleId: 'com.example.bda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzMFKOadBS9xbT7r-fpQvPYEP9RySjgBo',
    appId: '1:698030383095:web:512957df5f5c60d78998f2',
    messagingSenderId: '698030383095',
    projectId: 'abc-test-8a172',
    authDomain: 'abc-test-8a172.firebaseapp.com',
    storageBucket: 'abc-test-8a172.appspot.com',
  );

}